### ISSUE TITLE
Failure for regions without AZ

### ISSUE THREAD

**Issue by adstuart** [mattfeltonma/azure-site-recovery-demo#3]
FYI for region without AZ, the deploy-in-res part fails. e.g.

> {
<snip>
 failed validation with message: 'The zone(s) '1' for resource 'Microsoft.Compute/virtualMachines/vmwpri1cffe' is not supported. The supported zones for location 'northcentralus' are '''.'.\"\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by mattfeltonma** [comment]
Yep! In the Readme it’s stated this has to be deployed in to zones that support AZs. I’ll just remove the zones in the templates that don’t support AZs.
